#pragma once
// Global game-state machine (Godot's `Game` autoload).
#include "signal.h"
#include "actor.h"

// Selectable level / visual theme (chosen in the start menu or via the CLI).
// LEVEL_GRAVEYARD is the one non-boss level: a horde of Hollows instead.
enum Level { LEVEL_BLOODMOON = 0, LEVEL_FROZEN = 1, LEVEL_FORGE = 2, LEVEL_COLOSSEUM = 3, LEVEL_GRAVEYARD = 4, LEVEL_FUNGAL = 5, LEVEL_DESERT = 6, LEVEL_WRECK = 7, LEVEL_SANCTUM = 8, LEVEL_CLOCK = 9, LEVEL_SHRINE = 10, LEVEL_BONES = 11, LEVEL_GEODE = 12, LEVEL_TEMPLE = 13, LEVEL_MINE = 14, LEVEL_OBS = 15, LEVEL_LIB = 16, LEVEL_CAMP = 17, LEVEL_AQUA = 18, LEVEL_COURT = 19, LEVEL_GARDEN = 20, LEVEL_BRIDGE = 21, LEVEL_BEACON = 22, LEVEL_MILL = 23, LEVEL_OSSUARY = 24, LEVEL_FAIR = 25, LEVEL_THRONE = 26, LEVEL_SPRINGS = 27, LEVEL_PFOREST = 28, LEVEL_HAMLET = 29, LEVEL_HENGE = 30, LEVEL_BOG = 31, LEVEL_SAWMILL = 32, LEVEL_GAOL = 33, LEVEL_TAR = 34, LEVEL_VINE = 35, LEVEL_FLOE = 36, LEVEL_QUARRY = 37, LEVEL_DOCK = 38, LEVEL_GLASS = 39, LEVEL_APIARY = 40, LEVEL_KILN = 41, LEVEL_REEF = 42, LEVEL_FOUNDRY = 43, LEVEL_NAVE = 44, LEVEL_WATERMILL = 45, LEVEL_SALT = 46, LEVEL_STILT = 47, LEVEL_HIVE = 48, LEVEL_BREW = 49, LEVEL_BAMBOO = 50, LEVEL_COLLIER = 51, LEVEL_PLAZA = 52, LEVEL_PUMPKIN = 53, LEVEL_BELL = 54, LEVEL_AVIARY = 55, LEVEL_WEB = 56, LEVEL_LOTUS = 57, LEVEL_ARCHTREE = 58, LEVEL_CHESS = 59, LEVEL_MAZE = 60, LEVEL_FALLS = 61, LEVEL_CRATER = 62, LEVEL_TITAN = 63, LEVEL_HOODOO = 64, LEVEL_MOAI = 65, LEVEL_CAVERN = 66, LEVEL_PINES = 67, LEVEL_GALLEON = 68, LEVEL_SUNFLOWER = 69, LEVEL_SPHINX = 70, LEVEL_DAM = 71, LEVEL_THEATRE = 72, LEVEL_WHEEL = 73, LEVEL_REDWOOD = 74, LEVEL_BALLOON = 75, LEVEL_CANAL = 76, LEVEL_SILO = 77, LEVEL_ORGAN = 78, LEVEL_HYPO = 79, LEVEL_FORT = 80, LEVEL_TRIUMPH = 81, LEVEL_ORCHARD = 82, LEVEL_LOOM = 83, LEVEL_SAVANNA = 84, LEVEL_MOSQUE = 85, LEVEL_TOTEM = 86, LEVEL_OASIS = 87, LEVEL_PAGODA = 88, LEVEL_STEPWELL = 89, LEVEL_JANTAR = 90, LEVEL_TERRACOTTA = 91, LEVEL_BALLCOURT = 92, LEVEL_PETRA = 93, LEVEL_BAZAAR = 94, LEVEL_SIEGE = 95, LEVEL_WHALING = 96, LEVEL_CACTUS = 97, LEVEL_ZIMBABWE = 98, LEVEL_BASIL = 99, LEVEL_PRINT = 100, LEVEL_GER = 101, LEVEL_ALCHEMY = 102, LEVEL_BATHS = 103, LEVEL_FLOAT = 104, LEVEL_ISHTAR = 105, LEVEL_TANNERY = 106, LEVEL_MUSEUM = 107, LEVEL_GOMPA = 108, LEVEL_BUDDHA = 109, LEVEL_ANGKOR = 110, LEVEL_BADGIR = 111, LEVEL_TOPIARY = 112, LEVEL_GLASSWORKS = 113, LEVEL_SHIPYARD = 114, LEVEL_GOTHIC = 115, LEVEL_PUEBLO = 116 };
extern int g_level;

struct Game {
    enum State { TITLE, FIGHT, DEAD, VICTORY };

    State  state = TITLE;
    Actor* player = nullptr;
    Actor* boss = nullptr;
    bool   paused = false;

    Signal<int> state_changed;
    Signal<>    player_died;
    Signal<>    boss_died;
    Signal<>    restart_requested;   // main wires this to the full reset

    void set_state(State s);
    void start_fight();
    void on_player_died();
    void on_boss_died();
    void request_restart();
};

extern Game g_game;
